### ISSUE TITLE
table view might produce an indefinite loop on loading image data

### ISSUE THREAD

**Issue by GGoetzelmann** [NCSU-Libraries/annona#56]
I have provided an annotationlist to the tag 
```
<iiif-annotation annotationurl='" + annotationList + "' styling='table_view:true'></iiif-annotation>
```
with multiple resources on multiple manifests - I have started to understand that this is not the intended way to use the annotation board, but it might be an easy mistake.

In doing so, it can happen that the full image URL is not derived properly (likely based on the wrong manifest). If that happens, the image is loaded indefinitely in quick succession. I think it happens due to the fallback trying to resolve image URLs for iiif v3.

This way it might put a lot of unwanted load on an iiif server by the client and the effect is only visible in the browser console, not in the browser itself.

**Comment by dnoneill** [comment]
It is also not a valid form of an annotation lists. It is considered an invalid formation according to spec. I will see what I can do about putting a warning about this invalid formation.

**Comment by GGoetzelmann** [comment]
Thank you for kindly letting me know, I am indeed still figuring out the spec details. Just wanted to let you know that in case anything goes wrong (and I wanted to give you my example for clarification), it might get thrown into an infinite loop.

**Comment by dnoneill** [comment]
@GGoetzelmann I actually double checked this, and it works even annotation lists that are formed incorrectly with multiple images. Can you provide me with the JSON for your example?

**Comment by dnoneill** [comment]
@GGoetzelmann Yes. that reference of the canvas is the problem. There is an error handling built into the application. Basically if the full image doesn't render correctly it will try to switch from full/full to full/max or from full/max to full/full in the url. Since the url in the second annotation can't ever rendered correctly because the application will only grab the first manifest for matching canvases to images, it was stuck in a loop trying to get the image to render properly. I have fixed this so it doesn't do that anymore.
